config/routes.rb
Rails.application.routes.draw do

  get 'segments/index'

  root "users#index"
  #get "/home", to: 'home#index'
  #get "/exam_segment/:id", to: 'users#exam_segment'

  resources :exams
  resources :users do
    # get :exam_segment, on: :collection
    collection do
      get :show_question
      get :exam_segment
      post :user_answer
      #get :segment_complete
    end
  end

  resources :segments do
    member do
      get :select_question
    end
  end
  resources :questions


  devise_for :users, path: 'devise'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  resourcify
  has_and_belongs_to_many :segments, dependent: :destroy
  has_many :choices, inverse_of: :question, dependent: :destroy
  has_many :answers, inverse_of: :question, dependent: :destroy
  #cocoon helper
  accepts_nested_attributes_for :choices, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  load_and_authorize_resource
  before_action :set_question, only: [:show, :edit]
  before_action :authenticate_user!, :only => [:show, :index]

  def index
    @questions = Question.paginate(page: params[:page], :per_page => 1)
  end

  def show
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was created successfully." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html {render :new}
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    question = Question.find(params[:id])
    @questions = Question.paginate(page: params[:page], :per_page => 1).order("created_at")

    if @questions.length > 0

      page = page
      # @questions.total_pages == @questions.current_page

      # redirect_to questions_path(page: @questions.current_page)
    end
    redirect_to questions_path(page: page)

    respond_to do |format|
      if question.update(question_params)
        format.js
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    @questions = Question.paginate(page: params[:page], :per_page => 1)
    respond_to do |format|
      format.js
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    #params.require(:question).permit(:question, :option_a, :option_b, :option_c, :option_d, :answer)
    params.require(:question).permit(:question,choices_attributes: [:id, :option],answers_attributes: [:id, :answer])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer_fields.html.erb
<div class="nested-fields">
  <%= f.label :answer %>
  <%= f.text_field :answer %>
  <%= link_to_remove_association "remove answer", f %>
</div>

app/views/questions/_choice_fields.html.erb
<div class="nested-fields">
  <%= f.label :option %>
  <%= f.text_field :option %>
  <%= link_to_remove_association "remove option", f %>
</div>

app/views/questions/_edit_modal.html.erb
<div id="question-edit" class="modal" role="dialog" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Question</h4>
      </div>
      <div class="modal-body">
        <%= form_for @question, remote: true do |f| %>
          <% if @question.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

              <ul>
              <% @question.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div>
            <%= f.label :question %>
            <%= f.text_area :question, id: :question_no %>
          </div>

          <div>
            <p><strong>Choices:</strong></p>

            <div class="choices">
              <%= f.simple_fields_for  :choices do |choice| %>
                <%= render 'choice_fields', f: choice%>
              <%end%>

              <div class="links">
                <%= link_to_add_association 'add option', f, :answers %>
              </div>
            </div>
          </div>

          <div>
            <p><strong>Answers:</strong></p>

            <div class="answers">
              <%= f.simple_fields_for  :answers do |answer| %>
                <%= render 'answer_fields', f: answer %>
              <%end%>

              <div class="links">
                <%= link_to_add_association 'add answer', f, :answers %>
              </div>
            </div>
          </div>

          <%= f.submit %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary close-btn" data-dismiss="modal" aria-hidden="true" >Close</button>
      </div>
    </div>
  </div>
</div>

app/views/questions/_form.html.erb
<%= simple_form_for @question do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %>
    <%= f.text_area :question %>
  </div>
  <div>
    <p><strong>Choices:</strong></p>

    <div class="choices">
      <%@question.choices.build%>
      <%= f.simple_fields_for  :choices do |choice| %>
        <%= render 'choice_fields', f: choice%>
      <%end%>

      <div class="links">
        <%= link_to_add_association 'add option', f, :choices %>
      </div>
    </div>
  </div>

  <br />

  <div>
    <p><strong>Answers:</strong></p>

    <div class="answers">
      <%@question.answers.build%>
      <%= f.simple_fields_for  :answers do |answer| %>
        <%= render 'answer_fields', f: answer %>
      <%end%>

      <div class="links">
        <%= link_to_add_association 'add answer', f, :answers %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/questions/_question.html.erb
<% @questions.each do |question| %>
  <tr>
    <td><%= question.question %></td>

    <td><%= link_to 'Show', question %></td>

    <td><%= link_to 'Edit', edit_question_path(question), data: {id: question.id}, remote: true, 'data-toggle' => "modal" %></td>

    <td><%= link_to 'Destroy', "javascript:void(0);", :class => "deletebutton",data: {id: question.id, url: question_path(question)}%>
    </td>
  </tr>
<% end %>

app/views/questions/destroy.js.erb
$('.questions').html("<%=j render('question')%>");
$(".my_pagination").text("");
<%if @questions.present?%>
  $(".my_pagination").append(<%= will_paginate @questions%>);
<%end%>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/edit.js.erb
$('.my-question').html("<%=j render('edit_modal')%>");
$('#question-edit').modal('show', {backdrop: 'static', keyboard: false});

app/views/questions/index.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>

<div class="row">
  <div class="col-md-8 ">
    <p id="notice"><%= notice %></p>

    <h1>Questions</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Question</th>
          <!-- <th>Option </th> -->
          <!-- <th>Option B</th>
          <th>Option C</th>
          <th>Option D</th>
          <th>Answer</th> -->
          <th>Actions</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="questions">
        <%= render partial: "question" %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Question', new_question_path %>

    <div class='my-pagination'>
      <%= will_paginate @questions, remote: true %>
    </div>
  </div>
</div>
<div class="my-question"></div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form'%>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %><br />
</p>

<%= link_to 'Back', questions_path %>

app/views/questions/update.js.erb
$('#question-edit').modal('hide');
$('.modal-backdrop').remove();
$(".question-names").html("<%=j render('question')%>");
$(".my_pagination").text("");
$(".my_pagination").append(<%= will_paginate @questions%>);