config/routes.rb
Rails.application.routes.draw do

  get 'segments/index'

  root "users#index"
  #get "/home", to: 'home#index'
  #get "/exam_segment/:id", to: 'users#exam_segment'

  resources :exams
  resources :users do
    # get :exam_segment, on: :collection
    collection do
      get :show_question
      get :exam_segment
      post :user_answer
      #get :segment_complete
    end
  end

  resources :segments do
    member do
      get :select_question
    end
  end
  resources :questions


  devise_for :users, path: 'devise'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/segment.rb
class Segment < ApplicationRecord
  resourcify
  belongs_to :exam
  has_and_belongs_to_many :questions, dependent: :destroy
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController

  load_and_authorize_resource
  before_action :set_segment, only: [:show, :edit]
  before_action :authenticate_user!, :only => [:show, :index]

  def index
    @segments = Segment.all
  end

  def show
  end

  def new
    @segment = Segment.new
  end

  def edit
  end

  def create
    @segment = Segment.new(segment_params)

    respond_to do |format|
      if @segment.save
        format.html { redirect_to @segment, notice: 'Segment was successfully created.' }
        format.json { render :show, status: :created, location: @segment }
      else
        format.html { render :new }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    segment = Segment.find(params[:id])
    @segments = Segment.all
    respond_to do |format|
      if segment.update(segment_params)
        format.js
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    segment = Segment.find(params[:id])
    segment.destroy
    @segments = Segment.all # After destroy give update list of all segment
    respond_to do |format|
      format.js
    end
  end

  private

    def set_segment
      @segment = Segment.find(params[:id])
    end

    def segment_params
      params.require(:segment).permit(:name , :exam_id)
    end

end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/_edit_modal.html.erb
<div id="segment-edit" class="modal" role="dialog" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Segment</h4>
      </div>
      <div class="modal-body">
        <%= form_for @segment, remote: true do |form| %>
          <% if @segment.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

              <ul>
              <% @segment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <%= form.text_field :name, id: :segment_name %>
          <%= form.select(:exam_id, Exam.all.collect {|u| [u.title, u.id]}, :prompt => 'Select') %>
          <%= form.submit %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary"" data-dismiss="modal" aria-hidden="true" >Close</button>
      </div>
    </div>
  </div>
</div>

app/views/segments/_form.html.erb
<%= form_with(model: segment, local: true) do |form| %>
  <% if segment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
      <% segment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :segment_name %>
  </div>

  <div class="field">
    <%= form.select(:exam_id, Exam.all.collect {|u| [u.title, u.id]}, :prompt => 'Select') %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/segments/_segment.html.erb
<% @segments.each do |segment| %>
  <tr>
    <td><%= segment.name %></td>
    <td><%= link_to 'Show', segment %></td>
    <td><%= link_to 'Edit', edit_segment_path(segment), data: {id: segment.id}, remote: true, 'data-toggle' => "modal" %></td>
    <td><%= link_to 'Destroy', "javascript:void(0);", :class => "deletebutton",data: {id: segment.id, url: segment_path(segment) } %></td>
    <td><%= link_to 'Add Question to this segment', select_question_segment_path(segment) %></td>
  </tr>
<% end %>

app/views/segments/destroy.js.erb
$('.segment-names').html("<%=j render('segment')%>");

app/views/segments/edit.html.erb
<h1>Editing Segment</h1>

<%= render 'form', segment: @segment %>

<%= link_to 'Show', @segment %> |
<%= link_to 'Back', segments_path %>

app/views/segments/edit.js.erb
$('.my-segment').html("<%=j render('edit_modal')%>");
$('#segment-edit').modal('show', {backdrop: 'static', keyboard: false});

app/views/segments/index.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>

<div class="row">
  <div class="col-md-6 ">
    <p id="notice"><%= notice %></p>

    <h1>Manage Segment</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Segment</th>
          <th>Actions</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="segment-names">
        <%= render partial: "segment" %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Segment', new_segment_path %>
  </div>
</div>
<div class="my-segment"></div>

app/views/segments/new.html.erb
<h1>New Segment</h1>

<%= render 'form', segment: @segment %>

<%= link_to 'Back', segments_path %>

app/views/segments/select_question.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h1>Questions To Be Select</h1>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_tag select_question_segment_path do %>

          <!--<%# if @errors && @errors.any? %>
            <div id="error_explanation">
              <h2>
                <%#= pluralize(@errors.count, "error") %>
                Require to attempt each question:
              </h2>
              <ul>
                <%# @errors.each do |msg| %>
                  <li><%#= msg %></li>
                <%# end %>
              </ul>
            </div>
          <%# end %>-->

          <% @questions.each do |question| %>
            <div class="field">
              <!-- <label>Question: <%#= question.question %></label> -->
              <%= check_box_tag :question %><label>Question: <%= question.question %></label>
            </div>
          <% end %>

          <%= submit_tag "Add_question" , id: "Add_question"%>
        <% end %>
      </div>
    </div>
    <%= link_to 'Back', segments_path %>
  </div>
</div>

app/views/segments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Segment:</strong>
  <%= @segment.name %>
</p>

<%= link_to 'Edit', edit_segment_path(@segment) %> |
<%= link_to 'Back', segments_path %>

app/views/segments/update.js.erb
$('#segment-edit').modal('hide');
$('.modal-backdrop').remove();
$(".segment-names").html("<%=j render('segment')%>");