config/routes.rb
Rails.application.routes.draw do

  get 'segments/index'

  root "users#index"
  #get "/home", to: 'home#index'
  #get "/exam_segment/:id", to: 'users#exam_segment'

  resources :exams
  resources :users do
    # get :exam_segment, on: :collection
    collection do
      get :show_question
      get :exam_segment
      post :user_answer
      #get :segment_complete
    end
  end

  resources :segments do
    member do
      get :select_question
    end
  end
  resources :questions


  devise_for :users, path: 'devise'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/exam.rb
class Exam < ApplicationRecord
  resourcify
  belongs_to :user
  has_many :segments, dependent: :destroy
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  load_and_authorize_resource
  before_action :set_exam, only: [:show, :edit]
  before_action :authenticate_user!, :only => [:show, :index]

  # # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = current_user.exams.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    exam = Exam.find(params[:id])
    @exams = Exam.all
    respond_to do |format|
      if exam.update(exam_params)
        format.js
      else
        format.html { render :edit }

      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    exam = Exam.find(params[:id])
    exam.destroy
    @exams = Exam.all
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:title)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_edit_modal.html.erb
<div id="exam-edit" class="modal" role="dialog" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <%= form_for @exam, remote: true do |form| %>
          <% if @exam.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

              <ul>
              <% @exam.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <%= form.text_field :title, id: :exam_title %>
          <%= form.submit %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary close-btn" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/exams/_exam.html.erb
<% @exams.each do |exam| %>
  <tr>
    <td class="exam-title"><%= exam.title %></td>
    <td><%= link_to 'Show', exam %></td>
    <td><%= link_to 'Edit', edit_exam_path(exam), data: {id: exam.id}, remote: true, 'data-toggle' => "modal" %>
    <td><%= link_to 'Destroy', "javascript:void(0);", :class => "deletebutton",data: {id: exam.id, url: exam_path(exam) } %>
    </td>
  </tr>
<% end %>

app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :exam_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exams/destroy.js.erb
$('.exam-titles').html("<%=j render('exam')%>");

app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/edit.js.erb
$('.my-class').html("<%=j render('edit_modal')%>");
$('#exam-edit').modal('show', {backdrop: 'static', keyboard: false});

app/views/exams/index.html.erb
<% content_for(:sidebar) do %>
  <%= render :partial => "layouts/sidebar" %>
<% end %>

<div class="row">
  <div class="col-md-6 ">
    <p id="notice"><%= notice %></p>

    <h1>Exams</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Actions</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class="exam-titles">
        <%= render partial: "exam" %>
      </tbody>
    </table>
    <br>

    <%= link_to 'New Exam', new_exam_path %>
  </div>
</div>
<div class="my-class"></div>

app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @exam.title %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>

app/views/exams/update.js.erb
$('#exam-edit').modal('hide');
$('.modal-backdrop').remove();
$(".exam-titles").html("<%=j render('exam')%>");